<a href="https://colab.research.google.com/github/Kamruzzamansust/Kamruzzamansust/blob/main/malaria1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy

import matplotlib.pyplot as plt
import tensorflow_datasets as tfds
from tensorflow.keras.layers import Conv2D, MaxPool2D,Dense, Flatten, InputLayer
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam


In [2]:
datasets , datasets_info = tfds.load('malaria',with_info = True,as_supervised = True, shuffle_files = True,
                                     split = ['train'])

In [3]:
dataset = datasets

In [4]:
dataset

[<_PrefetchDataset element_spec=(TensorSpec(shape=(None, None, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>]

In [5]:
for data in dataset[0].take(4):
  print(data)


(<tf.Tensor: shape=(145, 148, 3), dtype=uint8, numpy=
array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(133, 127, 3), dtype=uint8, numpy=
array([[[0, 0, 0],
        [0, 0, 0],
       

In [60]:
def splits(dataset, TRAIN_RATIO, VAL_RATIO, TEST_RATIO):
  DATASET_SIZE = len(dataset)

  train_dataset = dataset.take(int(TRAIN_RATIO*DATASET_SIZE))

  val_test_dataset = dataset.skip(int(TRAIN_RATIO*DATASET_SIZE))
  val_dataset = val_test_dataset.take(int(VAL_RATIO*DATASET_SIZE))

  test_dataset = val_test_dataset.skip(int(VAL_RATIO*DATASET_SIZE))
  return train_dataset, val_dataset, test_dataset

In [44]:
dataset[0]

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, None, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>

In [61]:
TRAIN_RATIO = 0.8
VAL_RATIO = 0.1
TEST_RATIO = 0.1

train_dataset, val_dataset, test_dataset = splits(dataset[0], TRAIN_RATIO, VAL_RATIO, TEST_RATIO )

In [62]:
train_dataset

<_TakeDataset element_spec=(TensorSpec(shape=(None, None, 3), dtype=tf.uint8, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>

In [10]:
#Dataset Visualization

In [12]:
# data preprocessing



In [13]:
# first resize the image
# Normalization

In [63]:
imsize = 224

def resize_rescale(image,label):
  return tf.image.resize(image , (imsize,imsize))/255.0 , label

In [64]:
train_dataset = train_dataset.map(resize_rescale)
val_dataset = val_dataset.map(resize_rescale)
test_dataset = test_dataset.map(resize_rescale)

In [65]:
for image , label in train_dataset.take(4):
  print(image ,label)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(224, 224, 3), dtype=float32) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0

In [66]:
Batch_Size  = 32
train_dataset= train_dataset.shuffle(buffer_size = 8 , reshuffle_each_iteration=True).batch(Batch_Size).prefetch(tf.data.AUTOTUNE)

In [67]:
Batch_Size  = 32
val_dataset= val_dataset.shuffle(buffer_size = 8 , reshuffle_each_iteration=True).batch(Batch_Size).prefetch(tf.data.AUTOTUNE)

In [59]:
Batch_Size  = 32
test_dataset= test_dataset.shuffle(buffer_size = 8 , reshuffle_each_iteration=True).batch(Batch_Size).prefetch(tf.data.AUTOTUNE)

In [68]:
# here we use lenet architecture in future we will introduvc advance architecture
model = tf.keras.Sequential([
    InputLayer(input_shape=(imsize, imsize, 3)),
    Conv2D(filters=6, kernel_size=5, strides=1, padding='valid', activation='sigmoid'),
    MaxPool2D(pool_size=2, strides=2),
    Conv2D(filters=16, kernel_size=5, strides=1, padding='valid', activation='sigmoid'),
    MaxPool2D(pool_size=2, strides=2),
    Flatten(),
    Dense(100, activation='sigmoid'),
    Dense(10, activation='sigmoid'),
    Dense(1, activation='softmax')  # 'softmax' for binary or multiclass classification
])

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 220, 220, 6)       456       
                                                                 
 max_pooling2d_12 (MaxPooli  (None, 110, 110, 6)       0         
 ng2D)                                                           
                                                                 
 conv2d_13 (Conv2D)          (None, 106, 106, 16)      2416      
                                                                 
 max_pooling2d_13 (MaxPooli  (None, 53, 53, 16)        0         
 ng2D)                                                           
                                                                 
 flatten_6 (Flatten)         (None, 44944)             0         
                                                                 
 dense_18 (Dense)            (None, 100)              

In [69]:
model.compile(
    optimizer = Adam(learning_rate = 0.01),
    loss = BinaryCrossentropy(),
    metrics =['accuracy']


)

In [72]:
history = model.fit(train_dataset,validation_data = val_dataset , epochs = 1 , verbose = 1)

689/689 [==============================] - 992s 1s/step - loss: 0.6955 - accuracy: 0.5001 - val_loss: 0.6931 - val_accuracy: 0.5034


In [75]:
model.save('Lenet')# in this method we can save both configuration and weights

In [76]:
# now we are going to save the model with HDF5 format

#it is a lightweight version of tensorflow model saving method

model.save('lenet.hdf5') # it will not suitable when woring with custom layersd



/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [77]:
lenet_model_load = tf.keras.models.load_model('lenet.hdf5')

In [78]:
lenet_model_load.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          (None, 220, 220, 6)       456       
                                                                 
 max_pooling2d_12 (MaxPooli  (None, 110, 110, 6)       0         
 ng2D)                                                           
                                                                 
 conv2d_13 (Conv2D)          (None, 106, 106, 16)      2416      
                                                                 
 max_pooling2d_13 (MaxPooli  (None, 53, 53, 16)        0         
 ng2D)                                                           
                                                                 
 flatten_6 (Flatten)         (None, 44944)             0         
                                                                 
 dense_18 (Dense)            (None, 100)              

In [81]:
# now we will see how to save only the weights

# Save wights Method

model.save_weights('weights/lenet_weights')

#saving to the google drive

from google.colab import drive


In [82]:
# mount the drive

drive.mount('/content/drive/')

Mounted at /content/drive/
